 [package]
name = "elara_log"
description = "[DEPRECATED] Project Elara's lightweight logging library for general-purpose use"
license = "Unlicense"
repository = "https://github.com/elaraproject/elara-log"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-time = "0.0.5"
